# Generated by Django 4.1.1 on 2023-04-19 15:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="posts",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
